package main;

import event.EventMenuSelected;
import form.Form_Produk;
import form.Form_Penjualan;
import form.Form_Dashboard;
import form.Form_Laporan;
import java.awt.Color;
import javax.swing.JComponent;

public class Main_Home extends javax.swing.JFrame {

    private Form_Dashboard home;
    private Form_Produk formPr;
    private Form_Penjualan formPn;
    private Form_Laporan formLp;

    public Main_Home() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        home = new Form_Dashboard();
        formPr = new Form_Produk();
        formPn = new Form_Penjualan();
        formLp = new Form_Laporan();
        menu.initMoving(Main_Home.this);
        menu.addEventMenuSelected(new EventMenuSelected() {
            @Override
                        public void selected(int index) {
                System.out.println("Index selected: " + index); // Debug log
                if (index == 0) {
                    setForm(home);
                    headerHome.setMenuName("  Dashboard");
                } else if (index == 1) {
                    setForm(formPr);
                    headerHome.setMenuName("  Produk");
                } else if (index == 2) {
                    setForm(formPn);
                    headerHome.setMenuName("  Penjualan");
                } else if (index == 4) {
                    setForm(formLp);
                    headerHome.setMenuName("  Laporan");
                } else if (index == 7) { // Ubah angka 7 sesuai dengan indeks menu logout yang muncul
                    int confirm = javax.swing.JOptionPane.showConfirmDialog(
                            Main_Home.this,
                            "Apakah Anda yakin ingin logout?",
                            "Konfirmasi Logout",
                            javax.swing.JOptionPane.YES_NO_OPTION
                    );
                    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                        Main_Login login = new Main_Login();
                        login.setVisible(true);
                        dispose();
                    } else {
                        setForm(home);
                    }
                }
            }
        });
        //  set when system open start with home form
        setForm(new Form_Dashboard());
    }

    private void setForm(JComponent com) {
        panelMenu.removeAll();
        panelMenu.add(com);
        panelMenu.repaint();
        panelMenu.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder = new swing.PanelBorder();
        panelMenu = new javax.swing.JPanel();
        menu = new komponen.Menu();
        headerHome = new komponen.HeaderHome();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1170, 657));

        panelMenu.setLayout(new java.awt.BorderLayout());

        menu.setMinimumSize(new java.awt.Dimension(162, 482));

        javax.swing.GroupLayout panelBorderLayout = new javax.swing.GroupLayout(panelBorder);
        panelBorder.setLayout(panelBorderLayout);
        panelBorderLayout.setHorizontalGroup(
            panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBorderLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(headerHome, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)))
        );
        panelBorderLayout.setVerticalGroup(
            panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderLayout.createSequentialGroup()
                .addComponent(headerHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private komponen.HeaderHome headerHome;
    private komponen.Menu menu;
    private swing.PanelBorder panelBorder;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
